# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ifiok
description:         'DevOps Engineer from somewhere'
url:                 https://ifiok.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ifiok Idiang
  url:               https://twitter.com/ifiokidiang
  email:             ifiok@ifiok.com

# Custom vars
version:             1.0.0
